// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace UmbraGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_ResultCritical);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_AbilityPowerCoefficient);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_AttackPowerCoefficient);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack_Primary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Basic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_EnemyBasic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SuperArmor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_ComboInput);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_HitWindow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_HitWindowBegin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_HitWindowTick);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_HitWindowEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_HitReceived);
}
